include: package:flutter_lints/flutter.yaml

linter:
  rules:
    implementation_imports: true
    prefer_relative_imports: false
    always_use_package_imports: true
    unnecessary_this: false
    prefer_single_quotes: true


